---
- name: Detectar alerta de disco en logs del journal
  hosts: all
  sources:
    - ansible.eda.journald:
        match: "ALERTA: El uso del disco en.*"

  rules:
    - name: Detectar mensaje de uso de disco alto
      condition: events.MESSAGE is defined and events.MESSAGE is search("ALERTA")
      action:
        run_job_template:
          name: T1_RHEL_5__Check_and_depure_RHEL_disk
          organization: Default
