---
- name: Play to create EC2 resources and finally a RHEL 8 instance.
  hosts: localhost
  gather_facts: no
  vars:
    aws_region: us-east-2
    vpc_name: VPCname
    aws_instance_type: t2.micro
    aws_instance_ami_id: ami-0ba62214afa52bec7
    aws_key_pair_name: ocpkey  
    number_of_instances: 1

    # RHEL 10 ami-0fe07c1aadd2e4ac9
    # Windows Server 2022 Base ami-0fd4271cf3adce206



  tasks:
    - name: Get VPC info by Name tag
      amazon.aws.ec2_vpc_net_info:
        region: "{{ aws_region }}"
        filters:
          "tag:Name": "{{ vpc_name }}"
      register: vpc_info

    - name: Get subnet info by VPC ID
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ aws_region }}"
        filters:
          vpc-id: "{{ vpc_info.vpcs[0].id }}"
      register: subnet_info

    - name: Show first Subnet ID found
      debug:
        msg: "Subnet ID is {{ subnet_info.subnets[0].id }}"
      register: my_subnet_id

    - name: Provision EC2 selected instance
      amazon.aws.ec2_instance:
        instance_type: "{{ aws_instance_type }}"
        image_id: "{{ aws_instance_ami_id }}"
        region: "{{ aws_region }}"
        count: "{{ number_of_instances }}"
        wait: yes
        key_name: "{{ aws_key_pair_name }}"
        network:
          assign_public_ip: yes
        vpc_subnet_id: "{{ subnet_info.subnets[0].id }}"
        tags:
          Name: "RHEL10-{{ inventory_hostname }}"
          Type: Linux
      register: ec2_result

    - name: Show instance public IP
      debug:
        msg: "Instance launched. Public IP: {{ ec2_result.instances[0].public_ip_address }}"
