---
- name: Get VPC id by VPC name
  hosts: localhost
  vars:
    aws_region: us-east-2
    vpc_name: automathon_pr_t1
    key-name: demo

  tasks:
    - name: Get VPC info by Name tag
      amazon.aws.ec2_vpc_net_info:
        region: "{{ aws_region }}"
        filters:
          "tag:Name": "{{ vpc_name }}"
      register: vpc_info

    - name: Get subnet info by VPC ID
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ aws_region }}"
        filters:
          vpc-id: "{{ vpc_info.vpcs[0].id }}"
      register: subnet_info

    - name: Get Key Pair info by name
      amazon.aws.ec2_key_info:
        region: "{{ aws_region }}"
        filters:
          key-name: "demo"
      register: key_info

    - name: Show Key Pair name and fingerprint
      debug:
        msg: >
          Key name: {{ key_info.key_pairs[0].key_name }},
          Fingerprint: {{ key_info.key_pairs[0].key_fingerprint }}

    - name: Show Subnet ID if found
      debug:
        msg: "Subnet ID is {{ subnet_info.subnets[0].id }}"
      when: subnet_info.subnets | length > 0