---
- name: Get VPC id by VPC name
  hosts: localhost
  vars:
    aws_region: us-east-2
    vpc_name: myCompanyVPCname

  tasks:
    - name: Get VPC info by Name tag
      amazon.aws.ec2_vpc_net_info:
        region: "{{ aws_region }}"
        filters:
          "tag:Name": "{{ vpc_name }}"
      register: vpc_info

    - name: Show VPC ID if found
      debug:
        msg: "VPC ID is {{ vpc_info.vpcs[0].id }}"
      when: vpc_info.vpcs | length > 0