---
- name: Get subnet ID by VPC name
  hosts: localhost
  gather_facts: no
  vars:
    aws_region: us-east-2
    vpc_name: myCompanyVPCname

  tasks:
    - name: Get VPC info by Name tag
      amazon.aws.ec2_vpc_net_info:
        region: "{{ aws_region }}"
        filters:
          "tag:Name": "{{ vpc_name }}"
      register: vpc_info

    - name: Fail if no VPC found
      fail:
        msg: "No VPC found with name '{{ vpc_name }}'"
      when: vpc_info.vpcs | length == 0

    - name: Get subnet info by VPC ID
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ aws_region }}"
        filters:
          vpc-id: "{{ vpc_info.vpcs[0].id }}"
      register: subnet_info

    - name: Show Subnet ID if found
      debug:
        msg: "Subnet ID is {{ subnet_info.subnets[0].id }}"
      when: subnet_info.subnets | length > 0