---
- name: Create WinServer 2022 EC2 instance.
  hosts: localhost
  gather_facts: no
  vars:
    aws_region: us-east-2
    vpc_name: team1
    aws_instance_type: t2.micro
    aws_instance_ami_id: ami-0fd4271cf3adce206
    aws_instance_name: "WinServer2022-{{ 99999 | random }}"
    aws_key_pair_name: demo  
    number_of_instances: 1

    # RHEL 9 ami-0a482bdfdf4a33e61
    # Windows Server 2022 Base ami-0fd4271cf3adce206

  tasks:
    - name: Get VPC info by Name tag
      amazon.aws.ec2_vpc_net_info:
        region: "{{ aws_region }}"
        filters:
          "tag:Name": "{{ vpc_name }}"
      register: vpc_info

    - name: Get subnet info by VPC ID
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ aws_region }}"
        filters:
          vpc-id: "{{ vpc_info.vpcs[0].id }}"
      register: subnet_info

    - name: Show first Subnet ID found
      debug:
        msg: "Subnet ID is {{ subnet_info.subnets[0].id }}"

    - name: Provision EC2 instances
      amazon.aws.ec2_instance:
        instance_type: "{{ aws_instance_type }}"
        key_name: "{{ aws_key_pair_name }}"
        image_id: "{{ aws_instance_ami_id }}"
        region: "{{ aws_region }}"
        count: "{{ number_of_instances }}"
        security_group: "ansible_tower_sg"
        wait: yes
        network:
          assign_public_ip: yes   
        vpc_subnet_id: "{{ subnet_info.subnets[0].id }}"
        user_data: |
          <powershell>
          net user Administrator "MySecurePassword123!"
          winrm quickconfig -force
          winrm set winrm/config/service/auth '@{Basic="true"}'
          winrm set winrm/config/service '@{AllowUnencrypted="true"}'
          Set-Item -Force WSMan:\localhost\Service\AllowUnencrypted $true
          Set-Item -Force WSMan:\localhost\Service\Auth\Basic $true
          Enable-PSRemoting -Force
          </powershell>

          <powershell>
          # Establecer contraseña del usuario Administrator (para pruebas, no para producción)
          net user Administrator "MySecurePassword123!"

          # Habilitar WinRM
          winrm quickconfig -force
          winrm set winrm/config/service/auth '@{Basic="true"}'
          winrm set winrm/config/service '@{AllowUnencrypted="true"}'
          Set-Item -Force WSMan:\localhost\Service\AllowUnencrypted $true
          Set-Item -Force WSMan:\localhost\Service\Auth\Basic $true
          Enable-PSRemoting -Force

          # Abrir puertos 5985 (HTTP) y 5986 (HTTPS) en el firewall de Windows
          netsh advfirewall firewall add rule name="WinRM_HTTP" dir=in action=allow protocol=TCP localport=5985
          netsh advfirewall firewall add rule name="WinRM_HTTPS" dir=in action=allow protocol=TCP localport=5986
          </powershell>
          
        tags:
          Name: "{{ aws_instance_name }}"
          Type: Windows
      register: ec2_result

    - name: Inspect ec2_result content
      debug:
        var: ec2_result
