---
- name: Configurar servicio web Flask en Windows con NSSM
  hosts: all
  collections:
    - ansible.windows
  become: false

  vars:
    python_installer_url: https://www.python.org/ftp/python/3.12.2/python-3.12.2-amd64.exe
    nssm_zip_url: https://nssm.cc/release/nssm-2.24.zip
    install_dir: C:\FlaskService
    nssm_dir: C:\nssm
    service_name: FlaskWebService
    python_path: 'C:\Program Files\Python312\python.exe'
    app_py_path: "{{ install_dir }}\\app.py"

  tasks:

    - name: Crear carpeta de instalación
      ansible.windows.win_file:
        path: "{{ install_dir }}"
        state: directory

    - name: Descargar instalador de Python
      ansible.windows.win_get_url:
        url: "{{ python_installer_url }}"
        dest: "{{ install_dir }}\\python-installer.exe"

    - name: Instalar Python
      ansible.windows.win_package:
        path: "{{ install_dir }}\\python-installer.exe"
        arguments: /quiet InstallAllUsers=1 PrependPath=1
        creates_path: "{{ python_path }}"

    - name: Instalar Flask usando PowerShell con ruta con espacios
      ansible.windows.win_shell: |
        & "{{ python_path }}" -m pip install flask
      args:
        creates: 'C:\Program Files\Python312\Lib\site-packages\flask'

    - name: Crear archivo app.py (escucha en puerto 8080)
      ansible.windows.win_copy:
        dest: "{{ app_py_path }}"
        content: |
          from flask import Flask
          app = Flask(__name__)

          @app.route('/')
          def hello():
              return "¡Hola desde Flask ejecutándose como servicio de Windows en el puerto 8080!"

          if __name__ == "__main__":
              app.run(host="0.0.0.0", port=8080)

    - name: Descargar NSSM
      ansible.windows.win_get_url:
        url: "{{ nssm_zip_url }}"
        dest: "{{ install_dir }}\\nssm.zip"

    - name: Extraer NSSM con PowerShell
      ansible.windows.win_shell: |
        Expand-Archive -Path "{{ install_dir }}\\nssm.zip" -DestinationPath "{{ nssm_dir }}" -Force
      args:
        creates: "{{ nssm_dir }}\\win64\\nssm.exe"

    - name: Listar contenido de la carpeta NSSM win64 (para debug)
      ansible.windows.win_shell: dir "{{ nssm_dir }}\\win64"
      register: nssm_dir_listing

    - name: Mostrar listado de NSSM win64
      debug:
        var: nssm_dir_listing.stdout_lines

    - name: Verificar que nssm.exe exista
      ansible.windows.win_stat:
        path: "{{ nssm_dir }}\\win64\\nssm.exe"
      register: nssm_exe_stat

    - name: Verificar que python.exe exista
      ansible.windows.win_stat:
        path: "{{ python_path }}"
      register: python_exe_stat

    - name: Verificar que app.py exista
      ansible.windows.win_stat:
        path: "{{ app_py_path }}"
      register: app_py_stat

    - name: Fail si no existe nssm.exe
      ansible.builtin.fail:
        msg: "El archivo nssm.exe no fue encontrado en {{ nssm_dir }}\\win64\\nssm.exe"
      when: not nssm_exe_stat.stat.exists

    - name: Fail si no existe python.exe
      ansible.builtin.fail:
        msg: "El archivo python.exe no fue encontrado en {{ python_path }}"
      when: not python_exe_stat.stat.exists

    - name: Fail si no existe app.py
      ansible.builtin.fail:
        msg: "El archivo app.py no fue encontrado en {{ app_py_path }}"
      when: not app_py_stat.stat.exists

    - name: Verificar si el servicio ya existe en registro
      ansible.windows.win_reg_stat:
        path: "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\{{ service_name }}"
      register: service_reg

    - name: Crear servicio con NSSM
      ansible.windows.win_command:
        argv:
          - "{{ nssm_dir }}\\win64\\nssm.exe"
          - install
          - "{{ service_name }}"
          - "{{ python_path }}"
          - "{{ app_py_path }}"
      when: not service_reg.exists
