---
- name: Configurar servicio web Flask en Windows con NSSM
  hosts: all
  collections:
    - ansible.windows
  become: false
  vars:
    python_installer_url: https://www.python.org/ftp/python/3.12.2/python-3.12.2-amd64.exe
    nssm_zip_url: https://nssm.cc/release/nssm-2.24.zip
    install_dir: C:\FlaskService
    nssm_dir: C:\nssm
    service_name: FlaskWebService
    python_path: C:\Python312\python.exe
    app_py_path: "{{ install_dir }}\\app.py"

  tasks:

    - name: Crear carpeta de instalación
      win_file:
        path: "{{ install_dir }}"
        state: directory

    - name: Descargar Python Installer
      win_get_url:
        url: "{{ python_installer_url }}"
        dest: "{{ install_dir }}\\python-installer.exe"

    - name:
