---
- name: Detectar alerta de disco en event stream
  hosts: all
  sources:
    - ansible.eda.event_stream:
        stream: "disk-alerts"

  rules:
    - name: Detectar mensaje de uso de disco alto
      condition: event.message is search("ALERTA: El uso del disco en.*")
      action:
        run_job_template:
          name: team1 check and depure RHEL disk
          organization: Default
