---
- name: Detectar alerta de disco en logs con sabre1041.eda
  hosts: all
  sources:
    - ansible.eda.file_watch:
        path: /var/log/messages
        pattern: "ALERTA: El uso del disco en.*"

  rules:
    - name: Detectar mensaje de uso de disco alto
      condition: event is defined
      action:
        run_job_template:
          name: team1 check and depure RHEL disk
          organization: Default