---
- name: Ejecutar tarea periódica cada 1 minuto
  hosts: all
  sources:
    - ansible.eda.timer:
        interval: 61   # 60 segundos = 1 minuto

  rules:
    - name: Ejecutar job template periódicamente
      condition: event is defined
      action:
        run_job_template:
          name: team1 check and depure RHEL disk
          organization: Default