---
- name: Detectar alerta de disco en logs con source file
  hosts: all
  sources:
    - ansible.eda.file:
        path: /var/log/messages
        pattern: "ALERTA: El uso del disco en.*"
        mode: tail      # lee nuevas líneas al final (modo "tail")

  rules:
    - name: Detectar mensaje de uso de disco alto
      condition: event is defined
      action:
        run_job_template:
          name: team1 check and depure RHEL disk
          organization: Default
